# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you'll see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sen llc
email: your-email@example.com
description: "空き家から、住まいと暮らしを育てる"
baseurl: "" # ユーザーサイトの場合は空にする
url: "https://sen-llc.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

# Netlify CMS (Decap) と連携するディレクトリ構成
collections:
  journal:
    output: true
    permalink: /journal/:title/
    sort_by: date

defaults:
  - scope:
    path: ""
    type: "journal"
    values:
      layout: journal
  
  - scope:
    path: ""
    values:
      image: "/assets/images"

# Sass/CSS設定
sass:
  style: compressed
