# ファイル: _config.yml
title: sen-llc
description: サイトの説明
baseurl: "" # ユーザーサイトの場合は空にする
url: "https://sen-llc.github.io" # あなたのGitHub Pagesのドメイン

# ビルド設定
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github

# GitHub Pages互換性のための設定
github: [metadata]
safe: true
