title: sen llc
description: "空き家から、住まいと暮らしを育てる"
baseurl: ""
url: "https://sen-llc.github.io"
markdown: kramdown

# Netlify CMS（Decap）と連携するディレクトリ構成
collections:
  journal:
    output: true
    permalink: /journal/:title/
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      layout: journal

  - scope:
      path: ""
    values:
      image: "/assets/images"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build設定
exclude:
  - node_modules
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

# Sass/CSS設定
sass:
  style: compressed
