title: 合同会社巛（sen llc）
description: 合同会社巛（sen llc）のウェブサイト
baseurl: ""
url: ""

# ビルド設定
markdown: kramdown
permalink: /:title/

# コレクション設定
collections:
  posts:
    output: true
    permalink: /journal/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
