collections:
  - name: "rental"
    label: "賃貸記事"
    folder: "_journal/rental"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "カテゴリー", name: "type", widget: "hidden", default: "rental" }
      - { label: "画像", name: "image", widget: "image" }

  - name: "design"
    label: "設計記事"
    folder: "journal/design"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "画像", name: "image", widget: "image" }
      - { label: "所在地", name: "location", widget: "string" }
      - { label: "面積", name: "area", widget: "string" }
      - { label: "用途", name: "usage", widget: "string" }
      - { label: "竣工", name: "completion", widget: "string" }
      - { label: "施工", name: "contractor", widget: "string" }

 - name: "news"
    label: "お知らせ"
    folder: "_journal/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "カテゴリー", name: "type", widget: "hidden", default: "news" }
      
